config-version: 2

name: elementary_demo
version: 1.0.0

profile: default

model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

clean-targets:
  - target
  - dbt_packages

models:
  elementary_demo:
    marts:
      +materialized: table
      +schema: marts
    staging:
      +materialized: view
      +schema: staging
  elementary:
    +schema: elementary
    enabled: "{{ target.name == 'prod' }}"

flags:
  require_explicit_package_overrides_for_builtin_materializations: false
